version: "3.7"
services:
  db:
    image: postgres:12-bullseye
    restart: always
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - app.env
    depends_on:
      - db
    networks:
      - default
    ports:
      - "80:80"
volumes:
  data: